# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: dialga-cmd.LucidGrasp
PackageVersion: 1.2.3
InstallerType: inno
Scope: machine
InstallModes:
  - interactive
  - silent
  - silentWithProgress
ElevationRequirement: elevatesSelf
UpgradeBehavior: install
ReleaseDate: "2026-10-06"
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/dialga-cmd/LucidGrasp/releases/download/v1.2.3/LucidGrasp_Setup_x64.exe
    InstallerSha256: 98a3cf293010796697a1f3007ecd7c1f16d5346e671827264f09a1551ef457ca
ManifestType: installer
ManifestVersion: 1.12.0